# Default Flow Configuration (Data-only)
# Stage order, retries, and hooks configuration

# Stage Progression
stages:
  - collect_client_id
  - collect_job_number
  - confirm_job
  - ask_action
  - collect_action_value
  - confirm_action
  - execute_action
  - goodbye

# Retry Configuration
retries:
  default: 2
  collect_client_id: 3
  collect_job_number: 3
  confirm_job: 1
  ask_action: 2
  collect_action_value: 3
  confirm_action: 1
  execute_action: 1

# Timeout Settings (seconds)
timeouts:
  default: 5
  collect_client_id: 5
  collect_job_number: 5
  confirm_job: 8
  ask_action: 10
  collect_action_value: 8
  confirm_action: 8
  execute_action: 30

# Webhook Hooks
hooks:
  onCallStart: true
  onCallEnd: true
  onRecordingAvailable: true
  onStageTransition: false
  onError: true
  onMaxRetriesExceeded: true

# Stage Transition Rules
transitions:
  collect_client_id:
    valid_input: collect_job_number
    invalid_input: collect_client_id
    timeout: collect_client_id
    max_retries: goodbye

  collect_job_number:
    valid_input: confirm_job
    invalid_input: collect_job_number
    timeout: collect_job_number
    max_retries: goodbye

  confirm_job:
    confirmation_yes: ask_action
    confirmation_no: collect_job_number
    timeout: confirm_job
    max_retries: goodbye

  ask_action:
    valid_action: collect_action_value
    invalid_action: ask_action
    timeout: ask_action
    max_retries: goodbye

  collect_action_value:
    valid_input: confirm_action
    invalid_input: collect_action_value
    timeout: collect_action_value
    max_retries: goodbye

  confirm_action:
    confirmation_yes: execute_action
    confirmation_no: ask_action
    timeout: confirm_action
    max_retries: goodbye

  execute_action:
    success: ask_action
    failure: ask_action
    system_error: goodbye

# Business Rules
business_rules:
  allow_multiple_actions_per_call: true
  require_confirmation_for_updates: true
  auto_end_after_successful_action: false
  max_actions_per_call: 5

# Error Handling
error_handling:
  max_consecutive_errors: 3
  escalate_to_human: false
  provide_callback_option: true
  log_all_errors: true
